apiVersion: v2
name: ibank
description: Umbrella chart for IBank microservices

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.0.0"

dependencies:
  - name: config
    version: "0.1.0"
    repository: "file://../config"
  - name: grafana
    version: "0.1.0"
    repository: "file://../grafana"
  - name: keycloak
    version: "0.1.0"
    repository: "file://../keycloak"
  - name: kafka
    version: "0.1.0"
    repository: "file://../kafka"
  - name: postgres
    version: "0.1.0"
    repository: "file://../postgres"
  - name: prometheus
    version: "0.1.0"
    repository: "file://../prometheus"
  - name: zipkin
    version: "0.1.0"
    repository: "file://../zipkin"
  - name: accounts-service
    version: "0.1.0"
    repository: "file://../accounts-service/chart"
  - name: blocker-service
    version: "0.1.0"
    repository: "file://../blocker-service/chart"
  - name: cash-service
    version: "0.1.0"
    repository: "file://../cash-service/chart"
  - name: exchange-service
    version: "0.1.0"
    repository: "file://../exchange-service/chart"
  - name: exrate-service
    version: "0.1.0"
    repository: "file://../exrate-service/chart"
  - name: front-service
    version: "0.1.0"
    repository: "file://../front-service/chart"
  - name: notify-service
    version: "0.1.0"
    repository: "file://../notify-service/chart"
  - name: transfer-service
    version: "0.1.0"
    repository: "file://../transfer-service/chart"
  # используется в *-service
  - name: srv
    version: "0.1.0"
    repository: "file://./charts/srv"
