name: ibank
services:
  confsrv:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: confsrv
        EXPOSE_PORT: 8888
    ports:
      - "8888:8888"
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8888/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  eureka:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: eureka
        EXPOSE_PORT: 8761
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8761/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: gateway
        EXPOSE_PORT: 8880
    ports:
      - "8880:8880"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
      # была ситуация когда в упор не видел front-service с сообщением
      # o.s.c.l.core.RoundRobinLoadBalancer      : No servers available for service: front-service
      # хотя в eureka front-service был, разрешилось перезапуском gateway, поэтому добавил
      # зависимость
      front-service:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8880/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # при использовании localhost примерно через минуту приходилось повторно авторизоваться
      # в web-интерфейсе (указанное значение используется для подписи токена в атрибуте iss)
      KC_HOSTNAME: host.docker.internal
      # порт в контейнере должен совпадать с портом, открытым на localhost т.к. порт фактического
      # подключения попадает в iss токена и в случае разных портов будет разный iss и ошибка
      # при авторизации по одному из токенов (явно зафиксировать порт для iss не удалось)
      KC_HTTP_PORT: 8954
      KC_HTTP_ENABLED: "true"
      # Включаем импорт реалма при старте
      KC_IMPORT: /opt/keycloak/data/import/ibank.realm.json
    command: ["start-dev", "--hostname-strict=false", "--import-realm"]
    ports:
      - "8954:8954"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

  postgres:
    image: postgres:17.2-alpine3.20
    restart: always
    # set shared memory limit (reason: https://hub.docker.com/_/postgres)
    shm_size: 128mb
    ports:
      - "8955:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      # run scripts for create roles and databases
      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  front-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: front-service
        USAGE_MODULE: accounts-service
        USAGE_MODULE2: cash-service
    ports:
      - "8961:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8080/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  accounts-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: accounts-service
        USAGE_MODULE: notify-service
    ports:
      - "8962:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8080/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  cash-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: cash-service
        USAGE_MODULE: accounts-service
        USAGE_MODULE2: notify-service
    ports:
      - "8963:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8080/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  notify-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: notify-service
    ports:
      - "8968:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8080/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  # Фиктивный сервис, который проверят healthcheck сервисов, от которых не зависят другие сервисы
  health-checker:
    image: alpine
    command: sh -c "exit 0"  # Ничего не делает, просто завершается
    depends_on:
      gateway:
        condition: service_healthy
      front-service:
        condition: service_healthy
      accounts-service:
        condition: service_healthy
      cash-service:
        condition: service_healthy
      notify-service:
        condition: service_healthy
volumes:
  postgres_data:
