name: ibank
services:
  confsrv:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: confsrv
        EXPOSE_PORT: 8888
    ports:
      - "8888:8888"
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8888/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  eureka:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: eureka
        EXPOSE_PORT: 8761
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8761/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: gateway
        EXPOSE_PORT: 8880
    ports:
      - "8880:8880"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8880/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  front-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: front-service
    ports:
      - "8961:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8080/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  accounts-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MODULE_NAME: accounts-service
    ports:
      - "8962:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://confsrv:8888
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      confsrv:
        condition: service_healthy
      eureka:
        condition: service_healthy
    healthcheck:
      test: >
        sh -c '
          curl -sf http://localhost:8080/actuator/health |
          grep -q '"'"'"status":"UP"'"'"' || exit 1
        '
      interval: 5s
      timeout: 5s
      retries: 10

  # Фиктивный сервис, который проверят healthcheck сервисов, от которых не зависят другие сервисы
  health-checker:
    image: alpine
    command: sh -c "exit 0"  # Ничего не делает, просто завершается
    depends_on:
      gateway:
        condition: service_healthy
      front-service:
        condition: service_healthy
      accounts-service:
        condition: service_healthy
