openapi: 3.0.3
info:
  title: Exchange service API
  description: API сервиса конвертации валют
  version: 1.0.0
tags:
  - name: Rate
    description: API получения текущих курсов валют
  - name: SetRate
    description: API установки текущих курсов валют
  - name: Exchange
    description: API для конвертации валюты
paths:
  /rates:
    get:
      tags:
        - Rate
      operationId: getRates
      summary: Получить текущие курсы валют к рублю
      responses:
        '200':
          description: Текущие курсы валют к рублю
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrentRate'
    post:
      tags:
        - SetRate
      operationId: setRates
      summary: Установить текущие курсы валют к рублю
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/RateShort'
      responses:
        '204':
          description: Операция выполнена
        '400':
          description: Неверный запрос (валидация не пройдена)
        '409':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /exchange:
    post:
      tags:
        - Exchange
      operationId: exchange
      summary: Выполняет конвертацию валюты
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeRequest'
      responses:
        '200':
          description: Конвертация выполнена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeResponse'
        '400':
          description: Неверный запрос (валидация не пройдена)
        '409':
          description: Ошибка при выполнении операции
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CurrentRate:
      type: object
      properties:
        currencyCode:
          type: string
          example: "USD"
          description: Код валюты (ISO 4217)
        currencyName:
          type: string
          example: "Доллар США"
          description: Название валюты
        rate:
          type: number
          format: decimal
          description: Курс к рублю
      required:
        - currencyCode
        - currencyName
        - rate
    RateShort:
      type: object
      properties:
        currencyCode:
          type: string
          example: "USD"
          description: Код валюты (ISO 4217)
        rate:
          type: number
          format: decimal
          description: Курс к рублю
      required:
        - currencyCode
        - rate
    ExchangeRequest:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          description: Сумма с двумя знаками после запятой
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          example: "USD"
          description: Валюта (ISO 4217)
        toCurrency:
          type: string
          description: Валюта конвертации
      required:
        - amount
        - currency
        - toCurrency
    ExchangeResponse:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          description: Сумма с двумя знаками после запятой
        currency:
          type: string
          description: Валюта (ISO 4217)
      required:
        - amount
        - currency
    ErrorResponse:
      type: object
      properties:
        error_code:
          type: integer
          format: int32
        error_message:
          type: string
      required:
        - error_code
        - error_message
