# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Для переопределения в chart/values.yaml уровня проекта
global:
  domain: "latest.local"

kibana-deps:
  fullnameOverride: "ibank-kibana"

  elasticsearch:
    hosts:
      - ibank-elasticsearch
    port: 9200

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: "ibank-kibana.{{ .Values.global.domain }}"

  savedObjects:
    configmap: "ibank-kibana-saved-objects-data"
