server.port: 8888 # Порт, на котором будет запущен Config Server

spring:
  application:
    name: confsrv
  profiles:
    active: native # Профиль native необходимо включать для поддержки хранилища в локальной файловой системе
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/ # Фолдер, из которого загружаются конфигурации
