openapi: 3.0.3
info:
  title: Transfer service API
  description: API для переводов
  version: 1.0.0
tags:
  - name: Transfer
paths:
  /transfer:
    post:
      tags:
        - Transfer
      operationId: transfer
      summary: Внесение наличных
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '204':
          description: Успешное зачисление
        '400':
          description: Неверный запрос
        '401':
          description: Не авторизован
        '409':
          description: Нужно окрыть счет в указанной валюте
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    TransferRequest:
      type: object
      properties:
        login:
          type: string
          description: Логин пользователя
        currency:
          type: string
          pattern: '^[A-Z]{3}$'
          example: "USD"
          description: Валюта (ISO 4217)
        amount:
          type: number
          format: decimal
          minimum: 0.01
          description: Сумма с двумя знаками после запятой
        toLogin:
          type: string
          description: Логин получателя
        toCurrency:
          type: string
          pattern: '^[A-Z]{3}$'
          example: "USD"
          description: Валюта получения (ISO 4217)
      required:
        - login
        - currency
        - amount
        - toLogin
        - toCurrency
    ErrorResponse:
      type: object
      properties:
        error_code:
          type: integer
          format: int32
        error_message:
          type: string
      required:
        - error_code
        - error_message
