# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Для переопределения в chart/values.yaml уровня проекта
global:
  domain: "latest.local"

elasticsearch-deps:
  fullnameOverride: "ibank-elasticsearch"

  # deploy Elasticsearch as a "single-node" cluster (one master node replica)
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
