spring:
  security:
    oauth2:
      client:
        registration:
          paysrv:
            client-id: paysrv
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer.url}/realms/${keycloak.realm}
          # явно задаем URL т.к. host отличается от указанного в токене значения issuer
          jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
