spring:
  security:
    oauth2:
      client:
        registration:
          ibank-service:
            client-id: ${spring.application.name}
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer.url}/realms/${keycloak.realm}
          # явно задаем URL т.к. host отличается от указанного в токене значения issuer
          jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
