# в более точном профиле нужно задать spring.r2dbc.url для исключения ошибки
spring:
  r2dbc:
    username: ${service.basename}_srv
    password: ${service.basename}_srv

    # Есть баг с невозвратом соединений в пул после использования, воспроизводится при уменьшении max-size < 10
    # Описан в:
    # [r2dbc-pool connection not released after cancel]
    # (https://stackoverflow.com/questions/68407202/r2dbc-pool-connection-not-released-after-cancel)
    # Вероятно исправлено в Reactor Core 3.4.14 согласно https://github.com/r2dbc/r2dbc-pool/issues/144,
    # но Spring на данный момент не совместим с этой версией (возникает ошибка после запуска)
    #
#    pool:
#      enabled: true                               # Включение пула соединений
#      initial-size: 10                            # Начальное количество соединений в пуле
#      max-size: 50                                # Максимальное количество соединений
#      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
#      max-life-time: 10m                          # Максимальное время жизни соединения
#      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения

  # развертывание схемы
  sql.init:
    encoding: utf-8
    mode: always
    schema-locations: classpath:db/schema.sql
    data-locations: classpath:db/initial-data.sql
