# Дефолтная настройка для большинства сервисов (кроме confsrv и eureka)
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# URL к Gateway для запросов из сервисов (если не задан, то определяется по регистрации gateway в eureka)
gateway.url:

logging:
  level:
    com.example.ibank: DEBUG
