# Настройки для запуска сервисов в docker (через docker-compose.yml, а также через testcontainers в тестах)

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

# URL по которому keycloak доступен (по сети) сервисам в docker
keycloak.url: http://keycloak:8954

# совпадает с заданным KC_HOSTNAME в docker-compose.yml, которое попадает в поле iss токена
keycloak.issuer.url: http://host.docker.internal:8954

# Хост и порт для подключения к PostgreSQL
postgres_host: postgres
postgres_port: 5432
