# Настройки для сервисов, выполняющих обращения к другим сервисам

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
        registration:
          ibank-service:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: ${spring.application.name}
            client-secret: ${spring.application.name}-Secret
            clientAuthenticationMethod: client_secret_post

# для уменьшения задержки между регистрацией сервиса в eureka и началом его использования
# другими сервисами
eureka:
  client:
    # Запрашивать обновления каждую секунду
    registry-fetch-interval-seconds: 1
    # Отправлять heartbeat каждую секунду
    lease-renewal-interval-in-seconds: 1
    # Быстрее исключать неактивные сервисы
    lease-expiration-duration-in-seconds: 2

# типовые настройки (возможно нужно уточнять)
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 5s  # Был 1 секунда - не хватало в тесте
        cancel-running-future: false
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        register-health-indicator: true
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
