# Настройки для запуска сервисов вне docker

gateway.url: http://localhost:8880

keycloak.url: http://localhost:8954

# Значение в поле iss для проверки токена (фиксируется за счет KC_HOSTNAME в docker-compose.yml,
# предполагается что keycloak запущен из docker)
keycloak.issuer.url: http://host.docker.internal:8954

# Хост и порт для подключения к PostgreSQL
postgres_host: localhost
postgres_port: 8955
