spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
        registration:
          intershop: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: intershop
            client-secret: klflKSD2KZQ2VAPMFO2KJFeQdOLRmZoY
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета
