server.port: 8880

# уменьшено время кэширования данных по сервисам из Eureka Server
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

management:
  endpoint:
    web:
      exposure:
        include: health  # явно включаем
    health:
      probes:
        enabled: true  # Включает /health/readiness и /health/liveness
      show-details: always
  health:
    readiness-state:
      enabled: true    # Активирует проверку readiness состояния приложения

spring:
  cloud:
    loadbalancer:
      configurations: health-check
      health-check:
        initial-delay: 1s
        interval: 2s
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # перенаправление на keycloak для тестирования
        # (способ получения токенов в тестах, обеспечивающий стабильный iss токена)
        - id: keycloak-itest
          uri: http://keycloak:8954
          predicates:
            - Path=/api/keycloak/**
          filters:
            - StripPrefix=2

        # запросы по API конкретных сервисов
        - id: accounts-route
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=2  # Удаляет /api/accounts

        - id: cash-route
          uri: lb://cash-service
          predicates:
            - Path=/api/cash/**
          filters:
            - StripPrefix=2

        - id: transfer-route
          uri: lb://transfer-service
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=2

        - id: blocker-route
          uri: lb://blocker-service
          predicates:
            - Path=/api/blocker/**
          filters:
            - StripPrefix=2

        - id: notify-route
          uri: lb://notify-service
          predicates:
            - Path=/api/notify/**
          filters:
            - StripPrefix=2

        # запрос по неизвестному API (возвращает HTTP 404)
        - id: api-not-found
          uri: no://op  # Специальный URI для "ничего не делать"
          predicates:
            - Path=/api/**
          filters:
            - SetStatus=404
          order: 10
        # остальное на фронт
        - id: front-external
          uri: lb://front-service
          predicates:
            - Path=/**
          order: 20
