service.basename: front
spring.application.name: ${service.basename}-service
spring.profiles.active: dev

# настраиваемые профили согласно функционалу сервиса (из Spring Cloud Config)
spring:
  profiles:
    include: client
