openapi: 3.0.3
info:
  title: Accounts service API
  description: API сервиса аккаунтов
  version: 1.0.0
tags:
  - name: User
    description: API для управления пользователями
paths:
  /users:
    post:
      tags:
        - User
      operationId: createUser
      summary: Регистрирует нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          description: Неверный запрос (валидация не пройдена)
        '409':
          description: Такой пользователь уже существует
  /users/{login}/validate:
    post:
      tags:
        - User
      operationId: validate
      summary: Проверяет наличие пользователя с указанным логином и паролем
      parameters:
        - name: login
          in: path
          required: true
          schema:
            type: string
            minLength: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          description: Неверный запрос (валидация не пройдена)
        '401':
          description: Неверные логин или пароль
  /users/{login}/password:
    put:
      tags:
        - User
      operationId: changePassword
      summary: Меняет пароль пользователя
      parameters:
        - name: login
          in: path
          required: true
          schema:
            type: string
            minLength: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '204':
          description: Пароль изменен
        '400':
          description: Неверный запрос (валидация не пройдена)
        '404':
          description: Пользователь не найден
components:
  schemas:
    UserCreate:
      type: object
      properties:
        login:
          type: string
          minLength: 1
          maxLength: 50
          example: "user123"
          description: Логин пользователя
        password:
          type: string
          minLength: 1
          maxLength: 100
          format: password
          example: "qwerty123"
          description: Пароль (непустой)
        userName:
          type: string
          minLength: 1
          maxLength: 100
          description: Фамилия Имя
        birthDate:
          type: string
          format: date
          description: Дата рождения
      required:
        - login
        - password
        - userName
        - birthDate
    UserInfo:
      type: object
      properties:
        login:
          type: string
          description: Логин пользователя
        userName:
          type: string
          description: Фамилия Имя
        birthDate:
          type: string
          format: date
          description: Дата рождения
      required:
        - login
        - userName
        - birthDate
    ValidateRequest:
      type: object
      properties:
        password:
          type: string
          minLength: 1
          description: Пароль
      required:
        - password
    ChangePasswordRequest:
      type: object
      properties:
        password:
          type: string
          minLength: 1
          maxLength: 100
          format: password
          example: "qwerty123"
          description: Пароль (непустой)
      required:
        - password
