openapi: 3.0.3
info:
  title: Accounts service API
  description: API сервиса аккаунтов
  version: 1.0.0
tags:
  - name: Auth
    description: Проверка пользователя
paths:
  /auth/validate:
    post:
      tags:
        - Auth
      operationId: validate
      summary: Проверяет пользователя и возвращает права доступа
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequest'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Неверный запрос (валидация не пройдена)
        '401':
          description: Неверные логин или пароль
  /auth/register:
    post:
      tags:
        - Auth
      operationId: register
      summary: Регистрирует нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Неверный запрос (валидация не пройдена)
        '409':
          description: Такой пользователь уже существует
components:
  schemas:
    ValidateRequest:
      type: object
      properties:
        login:
          type: string
          minLength: 3
          maxLength: 50
          example: "user123"
          description: Логин пользователя
        password:
          type: string
          minLength: 3
          maxLength: 100
          format: password
          example: "qwerty123"
          description: Пароль (минимум 3 символов)
      required:
        - login
        - password
    AuthResponse:
      type: object
      properties:
        login:
          type: string
          example: "user123"
          description: Логин пользователя
        roles:
          type: array
          items:
            type: string
          example: ["ROLE_USER"]
          description: Список ролей пользователя
      required:
        - login
        - roles
    RegisterRequest:
      type: object
      properties:
        login:
          type: string
          minLength: 3
          maxLength: 50
          example: "user123"
          description: Логин пользователя
        password:
          type: string
          minLength: 3
          maxLength: 100
          format: password
          example: "qwerty123"
          description: Пароль (минимум 3 символов)
        userName:
          type: string
          minLength: 1
          maxLength: 100
          description: Фамилия Имя
        birthDate:
          type: string
          format: date
          description: Дата рождения
      required:
        - login
        - password
        - userName
        - birthDate
    RegisterResponse:
      type: object
      properties:
        login:
          type: string
          example: "user123"
          description: Логин пользователя
      required:
        - login
