apiVersion: v1
kind: ConfigMap
metadata:
  name: ibank-logstash-config
  labels:
    app: logstash
data:
  {{- $files := .Files.Glob "config/*.conf" }}
  {{- range $path, $_ := $files }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
