{
 "title": "IBank",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Login",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (login, result) (\r\n  increase(ibank_authenticate_total{application=\"front-service\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Неуспешные переводы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (login, currency, to_login, to_currency) (\r\n  increase(ibank_transfer_error_total{application=\"front-service\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Обновление курсов валют",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "  floor((time() - ibank_currency_update_timestamp{app=\"ibank\", application=\"exchange-service\"})/60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Блокировка операций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (login, currency, to_login, to_currency) (\r\n  increase(ibank_operation_block_total{application=\"blocker-service\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Ошибка отправки уведомления",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (login) (\r\n  increase(ibank_notify_error{application=\"notify-service\"}[$__range])\r\n)",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}