apiVersion: v1
kind: ConfigMap
metadata:
  name: ibank-kibana-saved-objects-data
  labels:
    app: kibana
data:
  {{- $files := .Files.Glob "config/*.ndjson" }}
  {{- range $path, $_ := $files }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
